version: 2.1

orbs:
  flutter-orb: circleci/flutter@1.1.0

on:
  pull_request:
    
jobs:
  flutter_unit_tests:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
  
  flutter_build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/apk/production/release.apk
workflows:
  version: 2
  flutter_unit_tests:
    jobs:
      - flutter_unit_tests
  flutter_build:
    jobs:
      - flutter_build